<div class='container' id='content-wrapper'>
    <div class='row' id='primary'>
        <div class='span12' id='content' style="min-height:300px; background-color:white;padding:35px;margin-left:0" role='main'>
			<?php
			$title = 'Supprimer la Photo';
			$this->headTitle($title);
			$url = $this->url('photo', array('action' => 'delete', 'id'=>$this->id))
			?>
			<h1><?=$this->escapeHtml($title)?></h1>
			Etes-vous sûr de vouloir supprimer la photo "<?=$this->escapeHtml($photo->nom)?>" ?
			<form action="<?=$url?>" method="post">
			    <div>
			        <input type="hidden" name="id" value="<?=$photo->id?>" />
			        <input type="submit" name="del" value="Oui" />
			        <input type="submit" name="del" value="Non" />
			    </div>
			</form>
        </div>
    </div>
</div>