<div class='site-footer' id='colophon' role='contentinfo'>
                <div class='container'>
                    <div class='row-fluid' id='footer-body'>
                        <div class='cleanwidget  nopadding span4 bl_html section' id='column1'>
                            <div class='widget Text' id='Text1'>
                                <h2 class='title'>A propos</h2>
                                    <div class='widget-content'>
                                        <img alt="footer logo" src="../4.bp.blogspot.com/-EX4wW9bc3GA/U_hgZNG_lZI/AAAAAAAABZg/4_-oy3YGCME/s1600/footer-ad.png" / /><br />CMS créé pour un projet à l'ESGI
                                    </div>
                                    <div class='clear'></div>
                                    <span class='widget-item-control'>
                                        <span class='item-control blog-admin'>
                                            <a class='quickedit' href='http://www.blogger.com/rearrange?blogID=3012279342595805206&amp;widgetType=Text&amp;widgetId=Text1&amp;action=editWidget&amp;sectionId=column1' onclick='return _WidgetManager._PopupConfig(document.getElementById("Text1"));' target='configText1' title='Edit'>
                                                <img alt='' height='18' src='../img1.blogblog.com/img/icon18_wrench_allbkg.png' width='18'/>
                                            </a>
                                        </span>
                                    </span>
                                    <div class='clear'></div>
                            </div>
                        </div>
                        
                        <div class='span4 bl_newsletter section' id='column3'>
                        </div>
                        <div class='clear'></div>
                    </div>
                </div>
                <div class='footer' id='footer' itemscope='itemscope' itemtype='http://schema.org/WPFooter'>
                    <div class='container1 clearfix'>
                        <div class='go-top'>
                            <a href='#'><i class='fa fa-angle-up'></i></a>
                        </div>
                        <p>
                            Créé par le groupe 6
                        </p>
                    </div>
                </div>
            </div>