<?php
$title = 'Modifier l\'article';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('post', array('action' => 'edit', 'id'=>$this->id)));
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?=$this->form()->openTag($form)?>
<?=$this->formRow($form->get('id'))?>
<?=$this->formRow($form->get('titre'))?>
<?=$this->formRow($form->get('contenu'))?>
<?=$this->formRow($form->get('categorie_id'))?>
<?=$this->formRow($form->get('submit'))?>
<?=$this->form()->closeTag($form)?>