<?php
$form->setAttribute('action', $this->url('post'))
     ->prepare();

echo $this->form()->openTag($form);

$post = $form->get('post');

echo $this->formRow($post->get('nom'));
echo $this->formRow($post->get('contenu'));
//echo $this->formCollection($post->get('categories'));

$categorie = $post->get('categorie');

echo $this->formRow($categorie->get('nom'));

echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit'));

echo $this->form()->closeTag();