<div class='container' id='content-wrapper'>
    <div class='row' id='primary'>
        <div class='span9' id='content' role='main'>
            <div class='main section' id='main'>
                <div class='widget Blog' id='Blog1'>
                    <?php foreach($posts as $post) : ?>
                    <div class='post'>
                        <h3><?php echo $this->escapeHtml($post->getTitre());?></h3>
                        <span id='p6601262707509758029'><div dir="ltr" style="text-align: left;" trbidi="on">
                            <div class="separator" style="clear: both; text-align: center;">
                            </div>
                            <div style="background-color: white; border: 0px; color: #333333; font-family: Arial, sans-serif; font-size: 13px; line-height: 20.799999237060547px; margin: 0px; padding: 0px; text-align: center; vertical-align: baseline;">
                                <div class="separator" style="clear: both; text-align: center;">
                                </div>
                                <div class="separator" style="clear: both; text-align: center;">
                                    <a href="../1.bp.blogspot.com/-QARbmVl4PD4/U_d93j3FdzI/AAAAAAAABYs/FOka5aEA-dU/s1600/landscape1-750x450.jpg" imageanchor="1" style="margin-left: 0em; margin-right: 0em;"><img alt="Welcome to Addiction !" border="0" height="192" src="../1.bp.blogspot.com/-QARbmVl4PD4/U_d93j3FdzI/AAAAAAAABYs/FOka5aEA-dU/s1600/landscape1-750x450.jpg" title="" width="320" /></a>
                                </div>
                                <br />
                            </div>
                            <div style="background-color: white; border: 0px; color: #333333; font-family: Arial, sans-serif; font-size: 13px; line-height: 20.799999237060547px; margin: 0px; padding: 0px; text-align: center; vertical-align: baseline;">
                            <?php echo $this->escapeHtml($post->getContenu());?> 
                            </div>
                            <div style="float: right;padding: 35px 35px 15px;">
                                <a href="<?php echo $this->url('addComment', ['id' => $post->getId()]) ?>" style="color: cadetblue;font-size: .9em;text-decoration: underline;">Ajouter un commentaire</a>
                            </div>
                            </div>
                        </span>

                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class='span3' id='side-bar'>
            <div class='clear'></div>
            <div id='sidebar-wrap' itemscope='' itemtype='http://schema.org/WPSideBar'>
                <div class='sidebar section' id='sidebar'>
                    
                    <div class='widget PopularPosts' id='PopularPosts1'>
                        <h2>Popular Posts</h2>
                        <div class='widget-content popular-posts'>
                            <ul>
                                <dd>
                                    <img alt='Welcome to Addiction !' height='50' src='../1.bp.blogspot.com/-QARbmVl4PD4/U_d93j3FdzI/AAAAAAAABYs/FOka5aEA-dU/s72-c/landscape1-750x450.jpg' width='50'/>
                                    <a href='2014/07/welcome-to-addiction.html' rel='bookmark' title='          Nunc tincidunt, elit non cursus euismod, lacus augue ornare metus, egestas imperdiet nulla nisl quis mauris. Suspendisse a pharetr...'>Welcome to Addiction !</a>
                                    <div style='clear: both;'></div>
                                </dd>
                            </ul>
                        </div>
                    </div>
  
                    <div class='widget Label' id='Label1'>
                        <h2>Labels</h2>
                        <div class='widget-content list-label-widget-content'>
                            <ul>
                                <li>
                                <a href='search/label/Business.html'>Business</a>
                                </li>
                                
                            </ul>
                             <div class='clear'></div>
                            <span class='widget-item-control'>
                                <span class='item-control blog-admin'>
                                    <a class='quickedit' href='http://www.blogger.com/rearrange?blogID=3012279342595805206&amp;widgetType=Label&amp;widgetId=Label1&amp;action=editWidget&amp;sectionId=sidebar' onclick='return _WidgetManager._PopupConfig(document.getElementById("Label1"));' target='configLabel1' title='Edit'>
                                        <img alt='' height='18' src='../img1.blogblog.com/img/icon18_wrench_allbkg.png' width='18'/>
                                    </a>
                                </span>
                            </span>
                            <div class='clear'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class='clear'></div>
    </div>
</div>