<div class='container' id='content-wrapper'>
    <div class='row' id='primary'>
        <div class='span9' id='content' role='main'>
            <div class='main section' id='main'>
                <div class='widget Blog' id='Blog1'>
                    <?php foreach($posts as $post) : ?>
                    <div class='post'>
                        <h3><?php echo $this->escapeHtml($post->getTitre());?></h3>
                        <span id='p6601262707509758029'><div dir="ltr" style="text-align: left;" trbidi="on">
                            <div class="separator" style="clear: both; text-align: center;">
                            </div>
                            <div style="background-color: white; border: 0px; color: #333333; font-family: Arial, sans-serif; font-size: 13px; line-height: 20.799999237060547px; margin: 0px; padding: 0px; text-align: center; vertical-align: baseline;">
                                <div class="separator" style="clear: both; text-align: center;">
                                </div>
                                <div class="separator" style="clear: both; text-align: center;">
                                    <a href="../1.bp.blogspot.com/-QARbmVl4PD4/U_d93j3FdzI/AAAAAAAABYs/FOka5aEA-dU/s1600/landscape1-750x450.jpg" imageanchor="1" style="margin-left: 0em; margin-right: 0em;"><img alt="<?php if($post->photo !== null){
                                       echo $post->photo->getAlt();
                                    }?>" border="0" height="192" src="<?php if($post->photo !== null){
                                       echo $post->photo->getLien();
                                    }?>" title="" width="320" /></a>
                                </div>
                                <br />
                            </div>
                            <div style="background-color: white; border: 0px; color: #333333; font-family: Arial, sans-serif; font-size: 13px; line-height: 20.799999237060547px; margin: 0px; padding: 0px; text-align: center; vertical-align: baseline;">
                            <?php echo $this->escapeHtml($post->getContenu());?> 
                            </div>
                            <div style="float: right;padding: 35px 35px 15px;">
                                <a href="<?php echo $this->url('addComment', ['id' => $post->getId()]) ?>" style="color: cadetblue;font-size: .9em;text-decoration: underline;">Ajouter un commentaire</a>
                            </div>
                            </div>
                        </span>

                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class='span3' id='side-bar'>
            <div class='clear'></div>
            <div id='sidebar-wrap' itemscope='' itemtype='http://schema.org/WPSideBar'>
                <div class='sidebar section' id='sidebar'>
                    <?php for($i=0;$i<1;$i++){ ?>
                    <div class='widget PopularPosts' id='PopularPosts1'>
                        <h2><?php echo $this->escapeHtml($post->getTitre());?></h2>
                        <div class='widget-content popular-posts'>
                            <ul>
                                <dd>
                                    <img alt="<?php if($post->photo !== null){
                                       echo $post->photo->getAlt();
                                    }?>" border="0" height="192" src="<?php if($post->photo !== null){
                                       echo $post->photo->getLien();
                                    }?>" title="" width="320" />
                                    <div style='clear: both;'></div>
                                </dd>
                            </ul>
                        </div>
                    </div>
                    <?php } ?>
                    
                    <div class='widget Label' id='Label1'>
                        <h2>Labels</h2>
                        <div class='widget-content list-label-widget-content'>
                            <ul>
                                <?php foreach($categs as $categ) : ?>
                                <li>
                                <?php if($categ->getNom() !== null){
                                       echo $categ->getNom();
                                    }?>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                             <div class='clear'></div>
                            
                            <div class='clear'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class='clear'></div>
    </div>
</div>