<div class='site-footer' id='colophon' role='contentinfo'>
                <div class='container'>
                    <div class='row-fluid' id='footer-body'>
                        <div class='cleanwidget  nopadding span4 bl_html section' id='column1'>
                            <div class='widget Text' id='Text1'>
                                <h2 class='title'>About us</h2>
                                    <div class='widget-content'>
                                        <img alt="footer logo" src="../4.bp.blogspot.com/-EX4wW9bc3GA/U_hgZNG_lZI/AAAAAAAABZg/4_-oy3YGCME/s1600/footer-ad.png" / /><br />Addiction is Clean and Responsive Personal Blogger template. Its very Simple and light.
                                    </div>
                                    <div class='clear'></div>
                                    <span class='widget-item-control'>
                                        <span class='item-control blog-admin'>
                                            <a class='quickedit' href='http://www.blogger.com/rearrange?blogID=3012279342595805206&amp;widgetType=Text&amp;widgetId=Text1&amp;action=editWidget&amp;sectionId=column1' onclick='return _WidgetManager._PopupConfig(document.getElementById("Text1"));' target='configText1' title='Edit'>
                                                <img alt='' height='18' src='../img1.blogblog.com/img/icon18_wrench_allbkg.png' width='18'/>
                                            </a>
                                        </span>
                                    </span>
                                    <div class='clear'></div>
                            </div>
                        </div>
                        <div class='span4 Label section' id='column2'>
                            <div class='widget Label' id='Label2'>
                                <h2>Labels</h2>
                                    <div class='widget-content list-label-widget-content'>
                                        <ul>
                                            <li>
                                            <a dir='ltr' href='search/label/Business.html'>Business</a>
                                            </li>
                                            <li>
                                            <a dir='ltr' href='search/label/Gallery.html'>Gallery</a>
                                            </li>
                                            <li>
                                            <a dir='ltr' href='search/label/Games.html'>Games</a>
                                            </li>
                                            <li>
                                            <a dir='ltr' href='search/label/Life%20%26%20style.html'>Life &amp; style</a>
                                            </li>
                                            <li>
                                            <a dir='ltr' href='search/label/Slider.html'>Slider</a>
                                            </li>
                                            <li>
                                            <a dir='ltr' href='search/label/Sports.html'>Sports</a>
                                            </li>
                                            <li>
                                            <a dir='ltr' href='search/label/Technology.html'>Technology</a>
                                            </li>
                                            <li>
                                            <a dir='ltr' href='search/label/ver.html'>ver</a>
                                            </li>
                                        </ul>
                                        <div class='clear'></div>
                                        <span class='widget-item-control'>
                                            <span class='item-control blog-admin'>
                                                <a class='quickedit' href='http://www.blogger.com/rearrange?blogID=3012279342595805206&amp;widgetType=Label&amp;widgetId=Label2&amp;action=editWidget&amp;sectionId=column2' onclick='return _WidgetManager._PopupConfig(document.getElementById("Label2"));' target='configLabel2' title='Edit'>
                                                    <img alt='' height='18' src='../img1.blogblog.com/img/icon18_wrench_allbkg.png' width='18'/>
                                                </a>
                                            </span>
                                        </span>
                                        <div class='clear'></div>
                                    </div>
                            </div>
                        </div>
                        <div class='span4 bl_newsletter section' id='column3'>
                        </div>
                        <div class='clear'></div>
                    </div>
                </div>
                <div class='footer' id='footer' itemscope='itemscope' itemtype='http://schema.org/WPFooter'>
                    <div class='container1 clearfix'>
                        <div class='go-top'>
                            <a href='#'><i class='fa fa-angle-up'></i></a>
                        </div>
                        <p>
                            Created By <a href='http://www.soratemplates.com/' id='mycontent' title='Blogger Templates'>Sora Templates</a>
                        </p>
                    </div>
                </div>
            </div>