<div class='container' id='content-wrapper'>
    <div class='row' id='primary'>
        <div class='span12' id='content' style="min-height:300px; background-color:white" role='main'>
            <div class='main section' id='main'>
                <div class='widget Blog' id='Blog1'>
                    <div class='post'>
                        
                    </div>
                    
                
                </div>
            </div>
        </div>
        
        <div class='clear'></div>
    </div>
</div>