<?php
$title = 'Ajouter une Catégorie';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('categorie', array('action' => 'add', 'id'=>$this->id)));
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?=$this->form()->openTag($form)?>
<?=$this->formRow($form->get('id'))?>
<?=$this->formRow($form->get('nom'))?>
<?=$this->formRow($form->get('submit'))?>
<?=$this->form()->closeTag($form)?>