<div class='container' id='content-wrapper'>
    <div class='row' id='primary' style="background-color: white;margin-left: 0px;min-height: 300px;">
        <div class='span9' id='content' role='main'>
            <div class='main section' id='main'>
                <div class='widget Blog' id='Blog1'>
                    <div class='post'>
                        <h3>
                        Bienvenue sur notre super CMS !
                        </h3>
                    </div>
                    
                </div>
            </div>
        </div>
        
    </div>
</div>
